### ISSUE TITLE
`duplicated property settings detected`

### ISSUE THREAD

**Issue by ipcamit** [colabfit/colabfit-tools#19]
While inserting data I get following warning

> /database.py:1101: UserWarning: 3 duplicate property settings detected

what does this warning mean?

**Comment by jvita** [comment]
That just means that it detected that 3 of the properties that you inserted had identical property settings, so only a single PS document will be added instead of adding all 3. A similar warning would appear if you happened to have duplicate property instances, or duplicate configurations. It's not something to be worried about unless you expected all of your properties to have different settings.
