### ISSUE TITLE
Scalar vs Array properties

### ISSUE THREAD

**Issue by ipcamit** [colabfit/colabfit-tools#9]
Currently energy is returned as 1x1 array. This raises the question, shall colabfit be aware of array vs scalar properties? Ideally scalar properties shall return as scalar. 

eg:
```
> client.get_data("properties",fields=["energy-forces.energy"],query={"_id": "-7545167799866548821"})
> [array([-277.02844126])]
```

Shouldn't it be `[-277.02844126]`. Given that in actual database it is `energy: { 'source-value': -277.045331247, 'source-unit': 'eV' }`, so I guess it is colabfit-tools post processing issue.

**Comment by jvita** [comment]
Agreed, the default behavior should be to return a list of the raw values, rather than a list of values wrapped in `np.atleast_1d()` as was being done previously. I had been doing this previously because it made it safe to call `np.concatenate()` on the list if `concatenate=True`, but I've now replaced this with `np.vstack()` which can handle concatenating zero-dimensional arguments.
